<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-08BI0FN" name="teststeps.NewLoanTest" tests="25" failures="2" timestamp="2021-05-04T22:53:05 CST" time="4.840" errors="0">
  <testcase name="testNewLoan" time="0.156" classname="teststeps.NewLoanTest"/>
  <testcase name="testNewLoan" time="0.374" classname="teststeps.NewLoanTest"/>
  <testcase name="testNewLoan" time="0.172" classname="teststeps.NewLoanTest"/>
  <testcase name="testNewLoan" time="0.141" classname="teststeps.NewLoanTest"/>
  <testcase name="testNewLoan" time="0.188" classname="teststeps.NewLoanTest"/>
  <testcase name="testNewLoan" time="0.203" classname="teststeps.NewLoanTest"/>
  <testcase name="testNewLoan" time="0.140" classname="teststeps.NewLoanTest"/>
  <testcase name="testNewLoan" time="0.203" classname="teststeps.NewLoanTest"/>
  <testcase name="testNewLoan" time="0.187" classname="teststeps.NewLoanTest"/>
  <testcase name="testNewLoan" time="0.141" classname="teststeps.NewLoanTest"/>
  <testcase name="testNewLoan" time="0.140" classname="teststeps.NewLoanTest"/>
  <testcase name="testNewLoan" time="0.141" classname="teststeps.NewLoanTest"/>
  <testcase name="testNewLoan" time="0.187" classname="teststeps.NewLoanTest"/>
  <testcase name="testNewLoan" time="0.329" classname="teststeps.NewLoanTest"/>
  <testcase name="testNewLoan" time="0.140" classname="teststeps.NewLoanTest"/>
  <testcase name="testNewLoan" time="0.141" classname="teststeps.NewLoanTest"/>
  <testcase name="testNewLoan" time="0.172" classname="teststeps.NewLoanTest"/>
  <testcase name="testNewLoan" time="0.171" classname="teststeps.NewLoanTest"/>
  <testcase name="testNewLoan" time="0.390" classname="teststeps.NewLoanTest">
    <failure type="java.lang.AssertionError" message="expected [6] but found [5]">
      <![CDATA[java.lang.AssertionError: expected [6] but found [5]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:563)
at common.BaseTest.assertResponse(BaseTest.java:103)
at teststeps.NewLoanTest.testNewLoan(NewLoanTest.java:58)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
    </failure>
  </testcase> <!-- testNewLoan -->
  <testcase name="testNewLoan" time="0.187" classname="teststeps.NewLoanTest"/>
  <testcase name="testNewLoan" time="0.219" classname="teststeps.NewLoanTest"/>
  <testcase name="testNewLoan" time="0.124" classname="teststeps.NewLoanTest"/>
  <testcase name="testNewLoan" time="0.141" classname="teststeps.NewLoanTest"/>
  <testcase name="testNewLoan" time="0.265" classname="teststeps.NewLoanTest">
    <failure type="java.lang.AssertionError" message="expected [2] but found [5]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [5]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:563)
at common.BaseTest.assertResponse(BaseTest.java:103)
at teststeps.NewLoanTest.testNewLoan(NewLoanTest.java:58)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
    </failure>
  </testcase> <!-- testNewLoan -->
  <testcase name="testNewLoan" time="0.188" classname="teststeps.NewLoanTest"/>
</testsuite> <!-- teststeps.NewLoanTest -->
